server:
  port: 8080 # This is the default port anyway, but you can change it here
spring:
  application:
    name: random-number
  profiles:
    active: dev
  datasource:
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:local;create=true
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyTenSevenDialect
  liquibase:
    enabled: false
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds